# Generated by Django 3.2.15 on 2022-08-07 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220805_1843'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment_Intent',
        ),
    ]
