# Generated by Django 3.0.8 on 2022-08-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_user_bvn'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='bank',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='tin',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
